### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by NathanBaulch**
Just thought I'd contribute some typo fixes that I stumbled on. Nothing controversial (hopefully).

Use the following command to get a quick summary of the specific corrections made:
```shell
git diff HEAD^! --word-diff-regex='\w+' -U0 \
  | grep -E '\[\-.*\-\]\{\+.*\+\}' \
  | sed -r 's/.*\[\-(.*)\-\]\{\+(.*)\+\}.*/\1 \2/' \
  | sort | uniq -c | sort -n
```

FWIW, the typos are:
* spwan (7)
* formated (4)
* togetheer (3)
* shoud (2)
* ouput (1)
* increas (1)
* intendend (1)
* misslocated (1)
* unkown (1)

### CODE REVIEW

**Comment by MoLow** [comment]
thanks for the contribution! seems like snapshots need to be re-generated

**Comment by NathanBaulch** [comment]
My working tree was still clean after running `yarn test:update-snapshots`. 🤷

**Comment by MoLow** [comment]
`yarn test:update-snapshots` needs to be re-ran on multiple node versions. the [failure](https://github.com/MoLow/reporters/actions/runs/11005423991/job/30594318010?pr=129) is on node 22.9.0

**Comment by NathanBaulch** [comment]
Ah, I was running node 22.8. Upgraded and pushed fresh snapshots.

**Review by MoLow — APPROVED** [review]

**Pull request merged**
